### ISSUE TITLE
error when running demo

### ISSUE THREAD

**Issue by amirrezasalimi** [howard-hou/VisualRWKV#1]
hey
thanks for great work 
i tried to run the demo but got this error:
Python 3.10.6

```
guest@DESKTOP-TTBPHVB:~/rwkv/VisualRWKV$ python3 demo.py
load adapter:  <All keys matched successfully>
RWKV_JIT_ON 1 RWKV_CUDA_ON 0 RESCALE_LAYER 6

Loading models/RWKV-4-Pile-169M-20220807-8023.pth ...
Strategy: (total 12+1=13 layers)
* cuda [float16, float16], store 13 layers
0-cuda-float16-float16 1-cuda-float16-float16 2-cuda-float16-float16 3-cuda-float16-float16 4-cuda-float16-float16 5-cuda-float16-float16 6-cuda-float16-float16 7-cuda-float16-float16 8-cuda-float16-float16 9-cuda-float16-float16 10-cuda-float16-float16 11-cuda-float16-float16 12-cuda-float16-float16
emb.weight                        f16      cpu  50277   768
blocks.0.ln1.weight               f16   cuda:0    768
blocks.0.ln1.bias                 f16   cuda:0    768
blocks.0.ln2.weight               f16   cuda:0    768
blocks.0.ln2.bias                 f16   cuda:0    768
blocks.0.att.time_decay           f32   cuda:0    768
blocks.0.att.time_first           f32   cuda:0    768
blocks.0.att.time_mix_k           f16   cuda:0    768
blocks.0.att.time_mix_v           f16   cuda:0    768
blocks.0.att.time_mix_r           f16   cuda:0    768
blocks.0.att.key.weight           f16   cuda:0    768   768
blocks.0.att.value.weight         f16   cuda:0    768   768
blocks.0.att.receptance.weight    f16   cuda:0    768   768
blocks.0.att.output.weight        f16   cuda:0    768   768
blocks.0.ffn.time_mix_k           f16   cuda:0    768
blocks.0.ffn.time_mix_r           f16   cuda:0    768
blocks.0.ffn.key.weight           f16   cuda:0    768  3072
blocks.0.ffn.receptance.weight    f16   cuda:0    768   768
blocks.0.ffn.value.weight         f16   cuda:0   3072   768
blocks.0.ln0.weight               f16   cuda:0    768
blocks.0.ln0.bias                 f16   cuda:0    768
....................................................................................................................................................................................
blocks.11.ln1.weight              f16   cuda:0    768
blocks.11.ln1.bias                f16   cuda:0    768
blocks.11.ln2.weight              f16   cuda:0    768
blocks.11.ln2.bias                f16   cuda:0    768
blocks.11.att.time_decay          f32   cuda:0    768
blocks.11.att.time_first          f32   cuda:0    768
blocks.11.att.time_mix_k          f16   cuda:0    768
blocks.11.att.time_mix_v          f16   cuda:0    768
blocks.11.att.time_mix_r          f16   cuda:0    768
blocks.11.att.key.weight          f16   cuda:0    768   768
blocks.11.att.value.weight        f16   cuda:0    768   768
blocks.11.att.receptance.weight   f16   cuda:0    768   768
blocks.11.att.output.weight       f16   cuda:0    768   768
blocks.11.ffn.time_mix_k          f16   cuda:0    768
blocks.11.ffn.time_mix_r          f16   cuda:0    768
blocks.11.ffn.key.weight          f16   cuda:0    768  3072
blocks.11.ffn.receptance.weight   f16   cuda:0    768   768
blocks.11.ffn.value.weight        f16   cuda:0   3072   768
ln_out.weight                     f16   cuda:0    768
ln_out.bias                       f16   cuda:0    768
head.weight                       f16   cuda:0    768 50277
load projection:  <All keys matched successfully>
  0%|                                                                                           | 0/100 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/guest/rwkv/VisualRWKV/demo.py", line 23, in <module>
    image_embs = model.adapter.forward_task_embs(image)
  File "/home/guest/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/guest/rwkv/VisualRWKV/visualrwkv/components/adapter.py", line 114, in forward_task_embs
    visual_embs = self.encode_image(image)
  File "/home/guest/rwkv/VisualRWKV/visualrwkv/components/adapter.py", line 108, in encode_image
    self.t5_proj(self.vit(image).last_hidden_state)
  File "/home/guest/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/guest/.local/lib/python3.10/site-packages/transformers/models/vit/modeling_vit.py", line 583, in forward
    embedding_output = self.embeddings(
  File "/home/guest/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/guest/.local/lib/python3.10/site-packages/transformers/models/vit/modeling_vit.py", line 122, in forward
    embeddings = self.patch_embeddings(pixel_values, interpolate_pos_encoding=interpolate_pos_encoding)
  File "/home/guest/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/guest/.local/lib/python3.10/site-packages/transformers/models/vit/modeling_vit.py", line 181, in forward
    embeddings = self.projection(pixel_values).flatten(2).transpose(1, 2)
  File "/home/guest/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/guest/.local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/guest/.local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
```

**Comment by amirrezasalimi** [comment]
any hint please? i really like to test this 🥹

**Comment by HildaM** [comment]
> any hint please? i really like to test this 🥹

have you solve this problem? I am going to test this project?

**Comment by amirrezasalimi** [comment]
not yet @HildaM

**Comment by howard-hou** [comment]
@amirrezasalimi This bug was due to the RWKV embedding always being on the CPU. I have fixed it. The issue will also be closed. Additionally, a more powerful model will be released soon.
